[server]
enableStaticServing = true

[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Regular.otf"
style="normal"
weight=400

[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Bold.otf"
style="normal"
weight=700

[theme]
font="StabilGrotesk"
backgroundColor="#000000"
secondaryBackgroundColor="#333333"
textColor="#FFFFFF"
baseRadius="8px"
borderColor="#FAFAFA99"

[theme.sidebar]
backgroundColor="#333333"
textColor="#FAFAFA99"
